#!/bin/sh
# =============================================================================
# Tunnel Client Bootstrap Entrypoint
# =============================================================================
#
# Self-bootstrapping entrypoint for the FRP tunnel client.
# Calls the control plane API to get-or-create STCP credentials,
# writes frpc.toml, and exec's frpc.
#
# Required env vars:
#   CONTROL_PLANE_URL   - e.g. http://192.168.1.50:8002
#   CONTROL_PLANE_TOKEN - Agent token for CP API auth
#   FRP_AUTH_TOKEN       - FRP server auth token (must match frps.toml)
#
# Optional env vars:
#   FRP_SERVER_ADDR - FRP server address (default: derived from CONTROL_PLANE_URL)
#   FRP_SERVER_PORT - FRP server port (default: 7000)
#
# =============================================================================

set -e

log() { echo "[tunnel-bootstrap] $1"; }
die() { echo "[tunnel-bootstrap] ERROR: $1" >&2; exit 1; }

# ── Validate required env vars ──────────────────────────────────────────────

[ -z "$CONTROL_PLANE_URL" ] && die "CONTROL_PLANE_URL is required"
[ -z "$CONTROL_PLANE_TOKEN" ] && die "CONTROL_PLANE_TOKEN is required"
[ -z "$FRP_AUTH_TOKEN" ] && die "FRP_AUTH_TOKEN is required"

# ── Derive FRP_SERVER_ADDR from CONTROL_PLANE_URL if not set ────────────────

if [ -z "$FRP_SERVER_ADDR" ]; then
    # Strip protocol and port: http://host:8002 -> host
    FRP_SERVER_ADDR=$(echo "$CONTROL_PLANE_URL" | sed 's|.*://||' | cut -d: -f1 | cut -d/ -f1)
    log "Derived FRP_SERVER_ADDR=$FRP_SERVER_ADDR from CONTROL_PLANE_URL"
fi

FRP_SERVER_PORT="${FRP_SERVER_PORT:-7000}"

# ── Poll tunnel-config endpoint with retries ────────────────────────────────

API_URL="${CONTROL_PLANE_URL}/api/v1/agent/tunnel-config"
MAX_RETRIES=30
RETRY_INTERVAL=10
attempt=0

log "Requesting tunnel config from $API_URL ..."

while true; do
    attempt=$((attempt + 1))

    # wget writes body to stdout (-O -), HTTP errors go to stderr
    RESPONSE=$(wget -q -O - \
        --header="Authorization: Bearer ${CONTROL_PLANE_TOKEN}" \
        --header="Content-Type: application/json" \
        --post-data="" \
        "$API_URL" 2>/dev/null) && break

    if [ "$attempt" -ge "$MAX_RETRIES" ]; then
        die "Failed to get tunnel config after $MAX_RETRIES attempts ($(( MAX_RETRIES * RETRY_INTERVAL ))s)"
    fi

    log "Attempt $attempt/$MAX_RETRIES failed, retrying in ${RETRY_INTERVAL}s..."
    sleep "$RETRY_INTERVAL"
done

# ── Parse JSON response ─────────────────────────────────────────────────────
# Response: {"agent_id":"...","secret_key":"...","proxy_name":"...","message":"..."}
# token_urlsafe produces only [A-Za-z0-9_-] so grep/cut is safe here.

PROXY_NAME=$(echo "$RESPONSE" | grep -o '"proxy_name"[[:space:]]*:[[:space:]]*"[^"]*"' | cut -d'"' -f4)
SECRET_KEY=$(echo "$RESPONSE" | grep -o '"secret_key"[[:space:]]*:[[:space:]]*"[^"]*"' | cut -d'"' -f4)
AGENT_ID=$(echo "$RESPONSE" | grep -o '"agent_id"[[:space:]]*:[[:space:]]*"[^"]*"' | cut -d'"' -f4)

[ -z "$PROXY_NAME" ] && die "Failed to parse proxy_name from response"
[ -z "$SECRET_KEY" ] && die "Failed to parse secret_key from response"

log "Tunnel config received for agent=$AGENT_ID proxy=$PROXY_NAME"

# ── Write frpc.toml ─────────────────────────────────────────────────────────

CONFIG="/tmp/frpc.toml"

cat > "$CONFIG" << EOF
# Auto-generated by tunnel-client entrypoint
serverAddr = "${FRP_SERVER_ADDR}"
serverPort = ${FRP_SERVER_PORT}

auth.method = "token"
auth.token = "${FRP_AUTH_TOKEN}"

log.to = "console"
log.level = "info"

transport.poolCount = 2
transport.tcpMux = true

[[proxies]]
name = "${PROXY_NAME}"
type = "stcp"
localIP = "10.200.1.20"
localPort = 22
secretKey = "${SECRET_KEY}"
EOF

log "Config written to $CONFIG, starting frpc..."

# ── Exec frpc ────────────────────────────────────────────────────────────────

exec frpc -c "$CONFIG"
