"""
Tests for the Envoy proxy configuration.
"""

import pytest
import yaml


class TestEnvoyConfig:
    """Test Envoy configuration validity."""

    def test_envoy_config_exists(self, configs_dir):
        """Envoy config file should exist."""
        config_file = configs_dir / "envoy" / "envoy-enhanced.yaml"
        assert config_file.exists(), f"Envoy config not found at {config_file}"

    def test_envoy_config_valid_yaml(self, configs_dir):
        """Envoy config should be valid YAML."""
        config_file = configs_dir / "envoy" / "envoy-enhanced.yaml"
        content = config_file.read_text()

        try:
            config = yaml.safe_load(content)
            assert config is not None
        except yaml.YAMLError as e:
            pytest.fail(f"Invalid YAML: {e}")

    def test_envoy_config_has_listeners(self, configs_dir):
        """Envoy config should define listeners."""
        config_file = configs_dir / "envoy" / "envoy-enhanced.yaml"
        config = yaml.safe_load(config_file.read_text())

        assert "static_resources" in config
        assert "listeners" in config["static_resources"]
        assert len(config["static_resources"]["listeners"]) > 0

    def test_envoy_config_has_clusters(self, configs_dir):
        """Envoy config should define clusters."""
        config_file = configs_dir / "envoy" / "envoy-enhanced.yaml"
        config = yaml.safe_load(config_file.read_text())

        assert "static_resources" in config
        assert "clusters" in config["static_resources"]

    def test_envoy_config_has_admin(self, configs_dir):
        """Envoy config should have admin interface."""
        config_file = configs_dir / "envoy" / "envoy-enhanced.yaml"
        config = yaml.safe_load(config_file.read_text())

        assert "admin" in config
        assert "address" in config["admin"]

    def test_envoy_config_no_lua_filter(self, configs_dir):
        """Envoy config should not contain any Lua filter references."""
        config_file = configs_dir / "envoy" / "envoy-enhanced.yaml"
        content = config_file.read_text()
        assert "lua" not in content.lower() or "lua" in "failure", "Envoy config should not reference Lua filters"

    def test_envoy_config_has_local_ratelimit(self, configs_dir):
        """Envoy static config should have local_ratelimit filter."""
        config_file = configs_dir / "envoy" / "envoy-enhanced.yaml"
        content = config_file.read_text()
        assert "envoy.filters.http.local_ratelimit" in content, "Envoy config should have local_ratelimit filter"


class TestEnvoyProxySettings:
    """Test Envoy proxy configuration settings."""

    def test_proxy_listens_on_expected_port(self, configs_dir):
        """Envoy should listen on the expected proxy port."""
        config_file = configs_dir / "envoy" / "envoy-enhanced.yaml"
        config = yaml.safe_load(config_file.read_text())

        listeners = config["static_resources"]["listeners"]

        # Find the main proxy listener
        proxy_ports = []
        for listener in listeners:
            address = listener.get("address", {})
            socket_address = address.get("socket_address", {})
            port = socket_address.get("port_value")
            if port:
                proxy_ports.append(port)

        # Should have at least one listener
        assert len(proxy_ports) > 0, "No listener ports found"

    def test_proxy_has_access_logging(self, configs_dir):
        """Envoy should have access logging configured."""
        config_file = configs_dir / "envoy" / "envoy-enhanced.yaml"
        content = config_file.read_text()

        # Check for access log configuration
        assert "access_log" in content.lower() or "accesslog" in content.lower(), (
            "Envoy should have access logging configured"
        )


class TestEnvoyNativeFilters:
    """Test native Envoy filter configuration generated by config_generator."""

    def _generate_config(self, configs_dir):
        """Generate Envoy config from cagent.yaml for testing."""
        import sys

        sys.path.insert(0, str(configs_dir.parent / "services" / "warden"))
        from config_generator import ConfigGenerator

        gen = ConfigGenerator(str(configs_dir / "cagent.yaml"))
        gen.load_config()
        return gen.generate_envoy_config()

    def test_envoy_config_has_ext_authz(self, configs_dir):
        """Generated config should have ext_authz filter."""
        config = self._generate_config(configs_dir)
        listeners = config["static_resources"]["listeners"]
        http_filters = listeners[0]["filter_chains"][0]["filters"][0]["typed_config"]["http_filters"]

        filter_names = [f["name"] for f in http_filters]
        assert "envoy.filters.http.ext_authz" in filter_names, "Generated config should have ext_authz filter"

    def test_envoy_config_has_local_ratelimit(self, configs_dir):
        """Generated config should have local_ratelimit filter."""
        config = self._generate_config(configs_dir)
        listeners = config["static_resources"]["listeners"]
        http_filters = listeners[0]["filter_chains"][0]["filters"][0]["typed_config"]["http_filters"]

        filter_names = [f["name"] for f in http_filters]
        assert "envoy.filters.http.local_ratelimit" in filter_names, (
            "Generated config should have local_ratelimit filter"
        )

    def test_envoy_config_no_lua_filter(self, configs_dir):
        """Generated config should not have Lua filter."""
        config = self._generate_config(configs_dir)
        listeners = config["static_resources"]["listeners"]
        http_filters = listeners[0]["filter_chains"][0]["filters"][0]["typed_config"]["http_filters"]

        filter_names = [f["name"] for f in http_filters]
        assert "envoy.filters.http.lua" not in filter_names, "Generated config should not have Lua filter"

    def test_envoy_config_has_rate_limit_per_route(self, configs_dir):
        """Generated config should have per-route rate limit for domains with custom rate limits."""
        config = self._generate_config(configs_dir)
        listeners = config["static_resources"]["listeners"]
        virtual_hosts = listeners[0]["filter_chains"][0]["filters"][0]["typed_config"]["route_config"]["virtual_hosts"]

        # Find a virtual host with a domain that has custom rate limits (e.g., api.openai.com)
        found_per_route_rl = False
        for vhost in virtual_hosts:
            for route in vhost.get("routes", []):
                tpfc = route.get("typed_per_filter_config", {})
                if "envoy.filters.http.local_ratelimit" in tpfc:
                    found_per_route_rl = True
                    rl_config = tpfc["envoy.filters.http.local_ratelimit"]
                    assert "token_bucket" in rl_config
                    assert "max_tokens" in rl_config["token_bucket"]
                    break
            if found_per_route_rl:
                break

        assert found_per_route_rl, "Should have at least one route with per-route rate limit config"

    def test_envoy_config_ext_authz_has_credential_headers(self, configs_dir):
        """ext_authz filter should allow credential headers upstream."""
        config = self._generate_config(configs_dir)
        listeners = config["static_resources"]["listeners"]
        http_filters = listeners[0]["filter_chains"][0]["filters"][0]["typed_config"]["http_filters"]

        ext_authz = None
        for f in http_filters:
            if f["name"] == "envoy.filters.http.ext_authz":
                ext_authz = f
                break

        assert ext_authz is not None
        tc = ext_authz["typed_config"]
        assert tc["failure_mode_allow"] is True
        patterns = tc["http_service"]["authorization_response"]["allowed_upstream_headers"]["patterns"]
        header_names = [p["exact"] for p in patterns]
        assert "authorization" in header_names
        assert "x-credential-injected" in header_names

    def test_envoy_config_routes_have_tracking_headers(self, configs_dir):
        """Routes should have X-Real-Domain tracking header."""
        config = self._generate_config(configs_dir)
        listeners = config["static_resources"]["listeners"]
        virtual_hosts = listeners[0]["filter_chains"][0]["filters"][0]["typed_config"]["route_config"]["virtual_hosts"]

        found_tracking = False
        for vhost in virtual_hosts:
            for route in vhost.get("routes", []):
                headers_to_add = route.get("request_headers_to_add", [])
                for h in headers_to_add:
                    if h.get("header", {}).get("key") == "X-Real-Domain":
                        found_tracking = True
                        break
                if found_tracking:
                    break
            if found_tracking:
                break

        assert found_tracking, "Should have X-Real-Domain tracking header on at least one route"

    def test_envoy_config_access_log_has_request_id(self, configs_dir):
        """Generated config should include request_id in access log JSON format."""
        config = self._generate_config(configs_dir)
        listeners = config["static_resources"]["listeners"]
        hcm = listeners[0]["filter_chains"][0]["filters"][0]["typed_config"]
        access_logs = hcm["access_log"]
        assert len(access_logs) > 0, "Should have at least one access log"

        json_format = access_logs[0]["typed_config"]["log_format"]["json_format"]
        assert "request_id" in json_format, "Access log JSON format should include request_id"
        assert json_format["request_id"] == "%REQ(X-REQUEST-ID)%"

    def test_rpm_to_token_bucket(self, configs_dir):
        """_rpm_to_token_bucket should correctly convert RPM to token bucket config."""
        import sys

        sys.path.insert(0, str(configs_dir.parent / "services" / "warden"))
        from config_generator import ConfigGenerator

        # rpm >= 60: tokens_per_fill = rpm // 60, fill_interval = 1s
        result = ConfigGenerator._rpm_to_token_bucket(120, 20)
        assert result == {"max_tokens": 20, "tokens_per_fill": 2, "fill_interval": "1s"}

        result = ConfigGenerator._rpm_to_token_bucket(60, 10)
        assert result == {"max_tokens": 10, "tokens_per_fill": 1, "fill_interval": "1s"}

        # rpm < 60: tokens_per_fill = 1, fill_interval = {60 // rpm}s
        result = ConfigGenerator._rpm_to_token_bucket(30, 5)
        assert result == {"max_tokens": 5, "tokens_per_fill": 1, "fill_interval": "2s"}

        result = ConfigGenerator._rpm_to_token_bucket(10, 3)
        assert result == {"max_tokens": 3, "tokens_per_fill": 1, "fill_interval": "6s"}


class TestEnvoyXdsGeneration:
    """Test xDS config generation for Envoy file-based hot-reload."""

    def _get_generator(self, configs_dir):
        import sys

        sys.path.insert(0, str(configs_dir.parent / "services" / "warden"))
        from config_generator import ConfigGenerator

        gen = ConfigGenerator(str(configs_dir / "cagent.yaml"))
        gen.load_config()
        return gen

    def test_bootstrap_has_rds_reference(self, configs_dir):
        """Bootstrap should use RDS for dynamic route config."""
        gen = self._get_generator(configs_dir)
        bootstrap = gen.generate_envoy_bootstrap()
        hcm = bootstrap["static_resources"]["listeners"][0]["filter_chains"][0]["filters"][0]["typed_config"]
        assert "rds" in hcm
        assert "route_config" not in hcm  # no inline routes
        assert hcm["rds"]["route_config_name"] == "egress_routes"
        assert "path_config_source" in hcm["rds"]["config_source"]

    def test_bootstrap_has_cds_config(self, configs_dir):
        """Bootstrap should reference CDS file for dynamic clusters."""
        gen = self._get_generator(configs_dir)
        bootstrap = gen.generate_envoy_bootstrap()
        assert "dynamic_resources" in bootstrap
        cds_config = bootstrap["dynamic_resources"]["cds_config"]
        assert "path_config_source" in cds_config
        assert cds_config["path_config_source"]["path"] == "/etc/envoy/cds.yaml"

    def test_bootstrap_has_static_control_plane_cluster(self, configs_dir):
        """Bootstrap should have control_plane_api cluster (needed for ext_authz)."""
        gen = self._get_generator(configs_dir)
        bootstrap = gen.generate_envoy_bootstrap()
        clusters = bootstrap["static_resources"]["clusters"]
        names = [c["name"] for c in clusters]
        assert "control_plane_api" in names
        assert len(clusters) == 1  # only control_plane_api, domain clusters come from CDS

    def test_bootstrap_ext_authz_permissive(self, configs_dir):
        """Bootstrap ext_authz should use permissive upstream headers."""
        gen = self._get_generator(configs_dir)
        bootstrap = gen.generate_envoy_bootstrap()
        hcm = bootstrap["static_resources"]["listeners"][0]["filter_chains"][0]["filters"][0]["typed_config"]
        ext_authz = hcm["http_filters"][0]
        assert ext_authz["name"] == "envoy.filters.http.ext_authz"
        patterns = ext_authz["typed_config"]["http_service"]["authorization_response"]["allowed_upstream_headers"]["patterns"]
        assert {"safe_regex": {"google_re2": {}, "regex": ".*"}} in patterns

    def test_cds_has_domain_clusters(self, configs_dir):
        """CDS should contain typed cluster resources."""
        gen = self._get_generator(configs_dir)
        cds = gen.generate_envoy_cds()
        assert "resources" in cds
        assert len(cds["resources"]) > 0
        for r in cds["resources"]:
            assert r["@type"] == "type.googleapis.com/envoy.config.cluster.v3.Cluster"
            assert "name" in r

    def test_rds_has_route_configuration(self, configs_dir):
        """RDS should contain a single RouteConfiguration with virtual hosts."""
        gen = self._get_generator(configs_dir)
        rds = gen.generate_envoy_rds()
        assert "resources" in rds
        assert len(rds["resources"]) == 1
        rc = rds["resources"][0]
        assert rc["@type"] == "type.googleapis.com/envoy.config.route.v3.RouteConfiguration"
        assert rc["name"] == "egress_routes"
        assert len(rc["virtual_hosts"]) > 0

    def test_cds_rds_match_monolithic(self, configs_dir):
        """CDS clusters + RDS routes should match the monolithic config."""
        gen = self._get_generator(configs_dir)
        monolithic = gen.generate_envoy_config()
        cds = gen.generate_envoy_cds()
        rds = gen.generate_envoy_rds()

        # Clusters should match (minus control_plane_api which is static in bootstrap)
        monolithic_clusters = monolithic["static_resources"]["clusters"]
        monolithic_domain_clusters = [c for c in monolithic_clusters if c["name"] != "control_plane_api"]
        cds_clusters = [{k: v for k, v in r.items() if k != "@type"} for r in cds["resources"]]
        assert monolithic_domain_clusters == cds_clusters

        # Virtual hosts should match
        monolithic_vhosts = monolithic["static_resources"]["listeners"][0]["filter_chains"][0]["filters"][0]["typed_config"]["route_config"]["virtual_hosts"]
        rds_vhosts = rds["resources"][0]["virtual_hosts"]
        assert monolithic_vhosts == rds_vhosts
